# Site settings

title: "UKCSRA Social Media Image Generator"

description: "A tool to create images for use on Facebook, Twitter and Instagram."

baseurl: "/social" # the subpath of your site, e.g. /blog
url: "//civilservice.lgbt"
author: "Civil Service Rainbow Alliance"
logo: "/logo.png"

asset-path: "/assets"
image-path: "/img"
image-2x-path: "/img/@2x"

# Social settings
facebook-id: "119705998363968" # For Facebook OpenGraph integration
facebook-slug: "ukcsra" # Automatically pre-pends http://facebook.com/
twitter-username: "ukcsra" # Twitter handle i.e. joebloggs
github-username:  "ukcsra"
google-site-verification: "RA-YBjxyRYVSuSFAYLKkufs6gjme6kMcihoB2KgKrTA" # GSV code; proves domain ownership

# Analytics
disable-analytics: false # Switch to "false" to start GA logging
google-analytics: "UA-47423042-1" # GA ID code

# Plugins and build settings

permalink: pretty
markdown: kramdown
future: false
sass:
    sass_dir: _sass
    sourcemap: true

gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from